# Generated by Django 5.2.17 on 2026-08-04 16:47

from django.db import migrations, models

PRORITY_MAP = {
    'LOW': 1,
    'MEDIUM': 2,
    'HIGH': 3,
}

STATUS_MAP = {
    'TODO': 1,
    'IN_PROGRESS': 2,
    'DONE': 3,
}

def convert_text_to_int(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')

    for task in Task.objects.all():
        old_priority = str(task.priority).upper() if task.priority else 'LOW'
        old_status = str(task.status).upper() if task.status else 'TODO'

        task.priority_new = PRORITY_MAP.get(old_priority, 1)
        task.status_new = STATUS_MAP.get(old_status, 1)
        task.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        #STEP 1: Create temporary column
        migrations.AddField(
            model_name='task',
            name='priority_new',
            field=models.IntegerField(default=1)
        ),
        migrations.AddField(
            model_name='task',
            name='status_new',
            field=models.IntegerField(default=1)
        ),

        #STEP 2: Run python code to rewrite data to new column
        migrations.RunPython(convert_text_to_int),

        #STEP 3: Remove old text column
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        #STEP 4: Change names of new columns to target ones
        migrations.RenameField(
            model_name='task',
            old_name='priority_new',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='status_new',
            new_name='status',
        ),
    ]
